CREATE TABLE client
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT                                    NOT NULL,
    CONSTRAINT PK_CLIENT PRIMARY KEY (id)
);

CREATE TABLE device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    CONSTRAINT PK_DEVICE PRIMARY KEY (id)
);

CREATE TABLE contact
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      TEXT                                    NOT NULL,
    email     TEXT                                    NOT NULL,
    client_id BIGINT                                          ,
    CONSTRAINT PK_CONTACT PRIMARY KEY (id)
);

ALTER TABLE device
    ADD CONSTRAINT FK_DEVICE_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE contact
    ADD CONSTRAINT FK_CONTACT_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE contact
    ADD CONSTRAINT UC_CONTACT_EMAIL UNIQUE (email);